openapi: 3.0.3
info:
  title: NVA ENTITY SETTINGS API
  version: 0.0.1

paths:
  /:
    get:
      summary: Get settings for specified entity
      responses:
        '200':
          description: All the candidates